/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'status' : BookingStatus,
  'customer' : Principal,
  'stylistId' : string,
  'advancePayment' : bigint,
  'timestamp' : Time,
  'serviceId' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type ExternalBlob = Uint8Array;
export interface InventoryItem {
  'threshold' : bigint,
  'name' : string,
  'quantity' : bigint,
  'category' : string,
}
export interface SalonService {
  'name' : string,
  'description' : string,
  'durationMinutes' : bigint,
  'category' : ServiceCategory,
  'price' : bigint,
}
export type ServiceCategory = { 'popular' : null } |
  { 'seasonal' : null } |
  { 'classic' : null } |
  { 'trending' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface StylistProfile {
  'bio' : string,
  'name' : string,
  'experienceYears' : bigint,
  'beforeAfterPhotos' : Array<ExternalBlob>,
  'specialties' : Array<string>,
  'rating' : number,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInventoryItem' : ActorMethod<[InventoryItem], undefined>,
  'addService' : ActorMethod<[SalonService], undefined>,
  'addStylist' : ActorMethod<[StylistProfile], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[string, string, Time, bigint], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteInventoryItem' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[string], undefined>,
  'deleteStylist' : ActorMethod<[string], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[string], Booking>,
  'getBookingsByStatus' : ActorMethod<[BookingStatus], Array<Booking>>,
  'getBookingsByStylist' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerBookings' : ActorMethod<[Principal], Array<Booking>>,
  'getDailyEarnings' : ActorMethod<[], bigint>,
  'getEarningsByCategory' : ActorMethod<[], Array<[ServiceCategory, bigint]>>,
  'getInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getLowStockItems' : ActorMethod<[], Array<InventoryItem>>,
  'getService' : ActorMethod<[string], [] | [SalonService]>,
  'getServices' : ActorMethod<[], Array<SalonService>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getStylist' : ActorMethod<[string], [] | [StylistProfile]>,
  'getStylists' : ActorMethod<[], Array<StylistProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBookingStatus' : ActorMethod<[string, BookingStatus], undefined>,
  'updateInventoryItem' : ActorMethod<[InventoryItem], undefined>,
  'updateService' : ActorMethod<[SalonService], undefined>,
  'updateStylist' : ActorMethod<[StylistProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];